gap_user:
    resource: "@GAPUserBundle/Controller/"
    type:     annotation
    prefix:   /

gap_stock_management:
    resource: "@GAPStockManagementBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

logout:
    pattern: /logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"