##security:
#    providers:
#        main:
#            entity: { class: GAP\UserBundle\Entity\User, property: username }
#
#    encoders:
#        GAP\UserBundle\Entity\User: plaintext
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
#
#    firewalls:
#        main:
#            pattern: .*
#            provider:  main
#            form_login:
#                csrf_provider: form.csrf_provider
#                login_path: GAPUserLogin
#                check_path: login_check
#                use_forward:   false
#                failure_path:  null
#                default_target_path: /login
#                remember_me:   true
#            logout:
#                path:   logout
#                target: /
#            anonymous:    true
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        login:
#            pattern: ^/login$
#            anonymous: true
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: _security_check
#                login_path: _demo_login
#            logout:
#                path:   _demo_logout
#                target: _demo
#            #anonymous: ~
#            #http_basic:
#            #    realm: "Secured Demo Area"
#
#    access_control:
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/ , role: IS_AUTHENTICATED_ANONYMOUSLY }
#
# app/config/security.yml

security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        GAP\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: GAP\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            anonymous: true


        main:
            pattern:   ^/
            anonymous: false
            provider:  main
            form_login:
                login_path: GAPUserLogin
                check_path: login_check
            logout:
                path:   logout
                target: /

    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
