<?php

namespace GAP\StockManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BesoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BesoinRepository extends EntityRepository {

    public function getAll() {

        $qb = $this->createQueryBuilder('b')
            ->leftJoin('b.service', 's')
            ->addSelect('s')
            ->orderBy('b.date', 'DESC');


        return $qb->getQuery()->getResult();
    }
}
