<?php

namespace GAP\StockManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DistributeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributeurRepository extends EntityRepository
{
}
