<?php

namespace GAP\StockManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoleculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoleculeRepository extends EntityRepository
{
    public function getMoleculeQuery(){
        return $this->createQueryBuilder('M');

    }
}
